### ISSUE TITLE
If Dr. Brown self assigned our previous issue, do we have to submit a new on while also assigning it to Dr. Brown?

### ISSUE THREAD

**Issue by RitvikPrabhu** [CS6704-VT/Basics-Workshop#9]
A previous issue of mine was self-assigned by Dr. Brown earlier today, however I was just added into the organization. Should I create a new issue and assign it to Dr. Brown?

**Comment by RitvikPrabhu** [comment]
Welp, I cannot assign the issue to anyone still

**Comment by chbrown13** [comment]
No, it's fine
